name: Mechanics
main: com.patrickzhong.mechanics.Mechanics
version: 1

commands:
  johnCena:
    description: Plays My Time is Now by John Cena.
    usage: /<command>
  class:
    description: Opens the class selection GUI.
    usage: /<command>
  lightshow:
    description: Starts a spell lightshow.
    usage: /<command> <radius> <length>